# Default values for rsyslog.
# This is a YAML-formatted file.

replicaCount: 1

image:
  registry: registry.cn-shanghai.aliyuncs.com
  repository: jibutech/rsyslog-server
  pullPolicy: IfNotPresent
  pullSecrets: []
  tag: ""

pvc:
  enabled: false
  size: 10Gi
  storageClassName: standard
  storageClassOverride: False

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 514

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

rotatateSchedule: "0 * * * *"

logAll: True

dumpLogsToStdout: True

cronLogLevel: 8

syslogconf: |-
  *.* -/var/log/my.log
  # we only expect local traffic, so no point in DNS lookup of the FDQNs
  global(net.enableDNS="off")

logrotateconf: |-
  /var/log/my.log {
      rotate 3
      copytruncate
      size 100M
      missingok
      compress
      daily
  }

sidecars: []
