name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Alicloud Docker registry
      uses: docker/login-action@v1
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.ALI_REGISTRY_USER }}
        password: ${{ secrets.ALI_REGISTRY_PASS }}
    - name: Build the Docker image
      run: make image
    - name: push the Docker image
      run: make push
